### ISSUE TITLE
source maps problem with webstorm

### ISSUE THREAD

**Issue by Ragnoroct** [esbuild-kit/core-utils#11]
Hi, I was having a problem debugging code using tsx/esno in webstorm. It was stopping on the line right below my breakpoint but I could see the stack and stacktrace was accurate to the code.

I turned off the minify options and **the debugger stopped on the correct line/breakpoint**

Here's a small patch for what I did. It probably makes sense to open these esbuild options to some configuration option (or not).

```patch
Index: src/esbuild/index.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/esbuild/index.ts b/src/esbuild/index.ts
--- a/src/esbuild/index.ts	(revision e88d9d6db42a51012db1ffca2184bfc8e150793c)
+++ b/src/esbuild/index.ts	(date 1654128860033)
@@ -35,8 +35,8 @@
 		 * https://github.com/evanw/esbuild/issues/1296
 		 */
 		// minify: true, keepNames: true,
-		minifySyntax: true,
-		minifyWhitespace: true,
+		minifySyntax: false,
+		minifyWhitespace: false,
 
 		...extendOptions,
 	};
```

**Comment by privatenumber** [comment]
Happy to reopen once reproduction is provided.
