### ISSUE TITLE
esm-loader breaks stack trace for esm files

### ISSUE THREAD

**Issue by mshima** [esbuild-kit/core-utils#32]
error.mjs file
```
import { basename } from 'path';

throw new Error();
```

Execute
```
node --loader @esbuild-kit/esm-loader error.mjs
```

null file is generated:
```
(node:17049) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error
    at null.<anonymous> (/Users/mshima/git/error/null:3:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
```

**Comment by mshima** [comment]
To workaround add `return;` at
https://github.com/esbuild-kit/core-utils/blob/98221a86df2820efca223d99775495d3bf853eec/src/transform/transform-dynamic-import.ts#L21

mjs files and transpiled mts looks functional. Dynamic import looks to messing with the loader structure.

**Comment by mshima** [comment]
https://github.com/esbuild-kit/core-utils/pull/33 works for the initial test case but fails with:
```
import('path');

throw new Error();
```

**Comment by mshima** [comment]
By the way, this is important because it breaks jest/expect.toMatchInlineSnapshot.

**Comment by privatenumber** [comment]
I haven't had a chance to investigate this but sounds like a bug.

I will try to look into it soon. Thanks for the reproduction.

**Comment by privatenumber** [comment]
Thanks for the report.

Should be fixed in https://github.com/esbuild-kit/core-utils/releases/tag/v3.0.0, which is available from https://github.com/esbuild-kit/esm-loader/releases/tag/v2.5.0 or https://github.com/esbuild-kit/cjs-loader/releases/tag/v2.4.0
