### ISSUE TITLE
`checkEsModule` appears to have faulty logic?

### ISSUE THREAD

**Issue by jcbhmr** [esbuild-kit/core-utils#42]
https://github.com/esbuild-kit/core-utils/blob/bdf4ef3d701288fbf8cda6f3564b61fe86defcd0/src/transform/transform-dynamic-import.ts#L5-L13

vs

https://www.npmjs.com/package/tslib?activeTab=code
```js
function __importDefault(mod) {
  return (mod && mod.__esModule) ? mod : { default: mod };
}
```

👇 idea to change to:

```js
const checkEsModule = `.then((mod)=>(mod&&mod.__esModule)?mod:{default:mod})`
```

ref https://github.com/esbuild-kit/tsx/issues/281

**Comment by jcbhmr** [comment]
the other similar thing is `__importStar()` which might be the right thing since `x = await import("./totally-esm.cjs")` is the same as `import * as x from "./totally-esm.cjs"`

```js
export function __importStar(mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
}
```

**Comment by privatenumber** [comment]
Not really sure what you're saying, but if you can consolidate your thoughts and provide a demo of the bug on StackBlitz it would help me understand. For a Issue template, please follow the one in https://github.com/esbuild-kit/tsx.

Closing for now but happy to reopen later.
