### ISSUE TITLE
Please update esbuild to ~0.18.10

### ISSUE THREAD

**Issue by viceice** [esbuild-kit/core-utils#43]
Otherwise you get duplicate deps when using a newer esbuild on project.

![image](https://github.com/esbuild-kit/core-utils/assets/1798109/9bfb95b2-dea0-46f5-b2c4-73e86dc31f63)
![image](https://github.com/esbuild-kit/core-utils/assets/1798109/9bf39389-5127-4e62-8fee-b80807f470e6)

**Comment by privatenumber** [comment]
PR welcome

**Comment by viceice** [comment]
thanks, will send tomorrow 🤗

**Comment by viceice** [comment]
btw: it's working fine with newer version forced via yarn resolution 😉

**Comment by viceice** [comment]
done 🤗  
- #44
