### ISSUE TITLE
MODULE_NOT_FOUND from @esbuild-kit/cjs-loader due to core-utils update

### ISSUE THREAD

**Issue by Shinigami92** [esbuild-kit/core-utils#47]
### Problem

While updating `devDependencies`, `@esbuild-kit/core-utils` got updated from `3.1.0` to `3.2.0`, I now get following error when running my node server:

```node
node:internal/modules/cjs/loader:1048
  const err = new Error(message);
              ^

Error: Cannot find module './**/*'
Require stack:
- /path-to-project/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js
- /path-to-project/node_modules/.pnpm/bcrypt@5.1.0/node_modules/bcrypt/bcrypt.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at u.default._resolveFilename (/path-to-project/node_modules/.pnpm/@esbuild-kit+cjs-loader@2.4.2/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:1519)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at <anonymous> (/path-to-project/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js:86:22)
    at Object.<anonymous> (/path-to-project/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js:309:2)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Object.F (/path-to-project/node_modules/.pnpm/@esbuild-kit+cjs-loader@2.4.2/node_modules/@esbuild-kit/cjs-loader/dist/index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1091:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/path-to-project/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.11/node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js',
    '/path-to-project/node_modules/.pnpm/bcrypt@5.1.0/node_modules/bcrypt/bcrypt.js'
  ]
}

Node.js v20.5.1
```

### Expected behavior

No error  
When I use
<img width="300" alt="image" src="https://github.com/esbuild-kit/core-utils/assets/7195563/6d55e767-69cd-4670-9e07-f319744d498c">

everything is fine

### Minimal reproduction URL

-

### Version

v3.2.0

### Node.js version

v20.5.1

### Package manager

pnpm

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Could you work on a reproduction? I'd like to help debug but not sure if I can with just the trace.

**Comment by Shinigami92** [comment]
> Could you work on a reproduction? I'd like to help debug but not sure if I can with just the trace.

Yeah I can try, but give me some time, so I can extract it
I'm also working right now, so it could be in some hours...

**Comment by privatenumber** [comment]
I'm not sure if it will fix it but I just released https://github.com/esbuild-kit/core-utils/releases/tag/v3.2.1 to address a Node 12 compatibility issue.

FWIW, I tried installing `bcrypt` and it runs fine with the latest tsx, core-utils, and Node v20.5.1.

**Comment by Shinigami92** [comment]
Sadly it doesn't fixed it
Will try to create the repro in evening

**Comment by MariuzM** [comment]
Same for me this new version just killed it

**Comment by MariuzM** [comment]
This is sample lock file before and after 
<img width="901" alt="image" src="https://github.com/esbuild-kit/core-utils/assets/36937039/e74e5f0d-6682-4cd2-b3db-ed2f5806ee2c">

and this is hard to reproduce because i use tsx and that uses this peer deep that i dont really have control over. I regullary delete lock file just to check stability of deps like sometimes 2 times a day. and today i found this. Yesterday no issues

**Comment by privatenumber** [comment]
Can you provide a reproduction? As I said above, I can't really help if I cant debug.

**Comment by privatenumber** [comment]
Thanks, that helped.

I filed a bug in esbuild: https://github.com/evanw/esbuild/issues/3353

For now, I'll downgrade to v0.18

**Comment by Shinigami92** [comment]
Can confirm, 3.2.2 fixed it
